[package]
name = "nub"
version = "1.0.0"
edition = "2021"

authors = ["Kendrick Grünberg"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.0.5", features = ["derive"] }
ring = "0.16.20"
data-encoding = "2.3.2"
